corrections

diff --git a/.github/workflows/parsegithubissue.yaml b/.github/workflows/parsegithubissue.yaml
--- a/.github/workflows/parsegithubissue.yaml
+++ b/.github/workflows/parsegithubissue.yaml
@@ -99,13 +99,13 @@ jobs:
       - name: get aks resource details
         if: env.PROCESS_SUCCESS == 'true'
         continue-on-error: true
-        run: ./scripts/aks-resource-details.sh
+        run: ./scripts/aks/aks-resource-details.sh
 
       - name: process costs
         if: env.PROCESS_SUCCESS == 'true'
         continue-on-error: true
         run: |
-          python cost-calculator.py || echo "Calculating cost failed"
+          python ./scripts/cost-calculator.py || echo "Calculating cost failed"
 
       - name: Add cost details as a comment
         if: env.PROCESS_SUCCESS == 'true'
